### ISSUE TITLE
无法加载json

### ISSUE THREAD

**Issue by myktw** [w4123/MiraiNative-CrossPlatform#1]
**描述这个Bug**
无法正常加载json文件
**复现步骤**
将json和dll加入data\MiraiNative\plugins文件内控制台只加载了dll
dll和json下载地址: https://github.com/kyubotics/coolq-http-api/releases/tag/v4.15.0
**截图和日志**
![Snipaste_2021-02-19_03-09-40](https://user-images.githubusercontent.com/35424096/108408419-fc94c580-725f-11eb-9f5f-e07465e26daa.png)
![Snipaste_2021-02-19_03-09-19](https://user-images.githubusercontent.com/35424096/108408465-07e7f100-7260-11eb-9ec9-56930d8fc264.png)

**运行环境**
 - 操作系统：Linux amd64
 - `mirai core` 版本：2.4.0
 - `mirai console` 版本：2.4.0
 - `mirai native` 版本：2.0.0-beta.1-1
 - `Java` 运行时版本：11.0.10x64

**Comment by w4123** [comment]
可以看到你的插件都 **没有** 加载成功
请先确定插件是为Linux编译的
可以发一下```file xxx.dll```的输出

**Comment by myktw** [comment]
下面也附带了一个windows下运行的返回值193也是JSON文件丢失

**Comment by w4123** [comment]
发一下```file```的输出哦

**Comment by w4123** [comment]
如果插件没有加载成功是不会尝试加载Json的，所以会有Json文件缺失的提示……这里的确可以优化下
但是主要问题不在这里

**Comment by myktw** [comment]
![Snipaste_2021-02-19_17-08-07](https://user-images.githubusercontent.com/35424096/108482941-17ede800-72d5-11eb-939b-81ef50d2ad40.png)

**Comment by w4123** [comment]
你看到了，这些都不适用于Linux哦

**Comment by myktw** [comment]
是的，但是我也有在windows上运行返回值193也是JSON文件丢失

**Comment by w4123** [comment]
你的是32位的dll 不能在64位上用
